/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yingliangdu' at '5/17/16 3:17 PM' with Gradle 2.11
 *
 * @author yingliangdu, @date 5/17/16 3:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
